import os

from PySide6.QtGui import (QFontDatabase, QFont)


class FontInitialization:
    """
        This class stores  all the custom added fonts and allows them to be easily accessed
        and regenerated by different classes.
    """
    def __init__(self):
        self.loadFonts("Fonts/VanillaExtractRegular.ttf")
        self.loadFonts("Fonts/FukuCatch.otf")

    def loadFonts(self, fp):
        """
            Loads the font found at the given filepath

            Args:
                fp: The filepath of the file to be added to the font database.
        """
        current_directory = os.path.dirname(os.path.realpath(__file__))
        file = os.path.join(current_directory, fp)
        QFontDatabase.addApplicationFont(file.__str__())
