# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'creationdialog.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialog, QDialogButtonBox,
    QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QVBoxLayout, QWidget, QFileDialog)

import os
from Apps.StartupClasses import HomeController

class Ui_CreationView(object):
    """
          AUTOGENERATED FROM QT DESIGNER, original file can be found in Apps/UI directory

          The basic UI for the project creation window.

      """
    def setupUi(self, CreationView):
        if not CreationView.objectName():
            CreationView.setObjectName(u"CreationView")
        CreationView.setEnabled(True)
        CreationView.resize(395, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreationView.sizePolicy().hasHeightForWidth())
        CreationView.setSizePolicy(sizePolicy)
        CreationView.setMaximumSize(QSize(400, 300))
        font = QFont()
        font.setFamilies([u"Merge"])
        CreationView.setFont(font)
        CreationView.setStyleSheet(u"")
        self.buttonBox = QDialogButtonBox(CreationView)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.verticalLayoutWidget = QWidget(CreationView)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 10, 356, 211))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(u"label")
        font1 = QFont()
        font1.setFamilies([u"Fuku Catch"])
        font1.setPointSize(20)
        font1.setBold(False)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.lineEdit = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QSize(250, 25))
        self.lineEdit.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.lineEdit)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)

        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout.addWidget(self.pushButton_2)

        self.label_3 = QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_3)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(-1, -1, 50, -1)
        self.horizontalSpacer_8 = QSpacerItem(150, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_12.addItem(self.horizontalSpacer_8)

        self.label_9 = QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        font2 = QFont()
        font2.setFamilies([u"Merge"])
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setItalic(True)
        self.label_9.setFont(font2)

        self.horizontalLayout_12.addWidget(self.label_9)

        self.lineEdit_9 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMaximumSize(QSize(50, 16777215))

        self.horizontalLayout_12.addWidget(self.lineEdit_9)


        self.verticalLayout.addLayout(self.horizontalLayout_12)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(-1, -1, 50, -1)
        self.horizontalSpacer = QSpacerItem(150, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer)

        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font2)

        self.horizontalLayout_5.addWidget(self.label_2)

        self.lineEdit_2 = QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QSize(50, 16777215))

        self.horizontalLayout_5.addWidget(self.lineEdit_2)


        self.verticalLayout.addLayout(self.horizontalLayout_5)


        self.retranslateUi(CreationView)
        self.buttonBox.accepted.connect(CreationView.accept)
        self.buttonBox.rejected.connect(CreationView.reject)

        QMetaObject.connectSlotsByName(CreationView)
    # setupUi

    def retranslateUi(self, CreationView):
        CreationView.setWindowTitle(QCoreApplication.translate("CreationView", u"Create a New Project", None))
        self.label.setText(QCoreApplication.translate("CreationView", u"New Project", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("CreationView", u"Enter New Project Name...", None))
        self.pushButton.setText(QCoreApplication.translate("CreationView", u"Open File", None))
        self.pushButton_2.setText(QCoreApplication.translate("CreationView", u"Remove File", None))
        self.label_3.setText(QCoreApplication.translate("CreationView", u"No File Selected.", None))
        self.label_9.setText(QCoreApplication.translate("CreationView", u"Canvas Width", None))
        self.label_2.setText(QCoreApplication.translate("CreationView", u"Canvas Height", None))
    # retranslateUi

class NoiDialog(QFileDialog):
    """

    The file dialog used to open existing projects.

    """
    def __init__(self, controller):
        super().__init__()
        self.filename = self.getOpenFileName(self, caption="Open Existing Project", filter="VoronoiGen Files (*.noi)")
        controller.noiParser(self.filename[0])

class CreationDialog(QDialog):
    """

    The dialog used to create a new project.

    """

    def __init__(self, controller):
        super().__init__()

        self.controller = controller

        self.dialog = QFileDialog()

        self.ui = Ui_CreationView()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.open_file_dialog)
        self.ui.pushButton_2.clicked.connect(self.reset_file_dialog)

    def accept(self):
        # Allow controller to handle input logic.
        if self.controller.alterModel(self.ui.lineEdit.text(), self.ui.lineEdit_9.text(), self.ui.lineEdit_2.text()):
            self.controller.initializeMainApp()
            super().accept()
        return

    def reset_file_dialog(self):
        self.ui.label_3.setText("No File Selected.")
        self.controller.setFile("")

    def open_file_dialog(self):
        filename = self.dialog.getOpenFileName(self, caption="Open Data File",
            filter="CSV Files (*.csv);;Excel Files (*.xlsx *.xls *.xlsm *.xlsb *.odf *.ods *.odt)")
        if not filename:
            self.ui.label_3.setText("No File Selected.")
            self.controller.setFile("")
        else:
           if filename[0]:
                self.ui.label_3.setText(f"{os.path.basename(filename[0])}")
                self.controller.setFile(filename[0])
           else:
               self.ui.label_3.setText("No File Selected.")
               self.controller.setFile("")



